language: node_js
node_js:
  - "6"
cache:
  yarn: true
  # directories:
before_install:
  - npm i -g yarn
install:
  - yarn install
script:
  - yarn test
after_success:
  - ./node_modules/.bin/codecov
