language: node_js
node_js:
  - "6"
addons:
  sauce_connect: true
cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
before_install:
  - npm i -g yarn
install:
  - yarn global add codecov codeclimate-test-reporter codacy-coverage
  - yarn install
script:
  - yarn test
  - yarn build && NODE_ENV=production yarn nightwatch
after_success:
  # I can't decide which coverage service I like better... So lets use them all!
  - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
  - codecov
  - codeclimate-test-reporter < coverage.lcov
  - cat ./coverage.lcov | codacy-coverage
